<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="12" total="19" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-28T15:48:46 IST" name="Suite" finished-at="2021-03-28T15:48:46 IST" duration-ms="133">
    <groups>
      <group name="smoke">
        <method signature="Sample1.testA()[pri:0, instance:core_Java_1.Sample1@574b560f]" name="testA" class="core_Java_1.Sample1"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="Sample1.testA()[pri:0, instance:core_Java_1.Sample1@574b560f]" name="testA" class="core_Java_1.Sample1"/>
        <method signature="Sample1.testC()[pri:0, instance:core_Java_1.Sample1@574b560f]" name="testC" class="core_Java_1.Sample1"/>
        <method signature="Sample2.testC()[pri:0, instance:core_Java_1.Sample2@ba54932]" name="testC" class="core_Java_1.Sample2"/>
        <method signature="Sample3.testA()[pri:0, instance:core_Java_1.Sample3@28975c28]" name="testA" class="core_Java_1.Sample3"/>
        <method signature="Sample4.search()[pri:0, instance:core_Java_1.Sample4@3943a2be]" name="search" class="core_Java_1.Sample4"/>
        <method signature="Sample5.testB()[pri:0, instance:core_Java_1.Sample5@343570b7]" name="testB" class="core_Java_1.Sample5"/>
        <method signature="Sample6.testC()[pri:0, instance:core_Java_1.Sample6@157853da]" name="testC" class="core_Java_1.Sample6"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2021-03-28T15:48:46 IST" name="Test" finished-at="2021-03-28T15:48:46 IST" duration-ms="133">
      <class name="core_Java_1.Sample2">
        <test-method signature="testC()[pri:0, instance:core_Java_1.Sample2@ba54932]" started-at="2021-03-28T15:48:46 IST" name="testC" finished-at="2021-03-28T15:48:46 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testC -->
      </class> <!-- core_Java_1.Sample2 -->
      <class name="core_Java_1.Sample3">
        <test-method signature="testA()[pri:0, instance:core_Java_1.Sample3@28975c28]" started-at="2021-03-28T15:48:46 IST" name="testA" finished-at="2021-03-28T15:48:46 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
      </class> <!-- core_Java_1.Sample3 -->
      <class name="core_Java_1.Sample1">
        <test-method signature="testA()[pri:0, instance:core_Java_1.Sample1@574b560f]" started-at="2021-03-28T15:48:46 IST" name="testA" finished-at="2021-03-28T15:48:46 IST" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at core_Java_1.Sample1.testA(Sample1.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method signature="testC()[pri:0, instance:core_Java_1.Sample1@574b560f]" started-at="2021-03-28T15:48:46 IST" name="testC" finished-at="2021-03-28T15:48:46 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testC -->
      </class> <!-- core_Java_1.Sample1 -->
      <class name="core_Java_1.Sample6">
        <test-method signature="testC()[pri:0, instance:core_Java_1.Sample6@157853da]" started-at="2021-03-28T15:48:46 IST" name="testC" finished-at="2021-03-28T15:48:46 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [gmail] but found [Gmail]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [gmail] but found [Gmail]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at core_Java_1.Sample6.testC(Sample6.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testC -->
      </class> <!-- core_Java_1.Sample6 -->
      <class name="core_Java_1.Sample4">
        <test-method signature="search()[pri:0, instance:core_Java_1.Sample4@3943a2be]" started-at="2021-03-28T15:48:46 IST" name="search" finished-at="2021-03-28T15:48:46 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
      </class> <!-- core_Java_1.Sample4 -->
      <class name="core_Java_1.Sample5">
        <test-method signature="testB()[pri:0, instance:core_Java_1.Sample5@343570b7]" started-at="2021-03-28T15:48:46 IST" name="testB" finished-at="2021-03-28T15:48:46 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB -->
      </class> <!-- core_Java_1.Sample5 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
